# Generated by Django 3.2.25 on 2024-06-15 07:20

import discordBot_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reminder_date', discordBot_django.models.PSTDateTimeField()),
                ('original_message_channel_id', models.CharField(max_length=3000)),
                ('original_message_id', models.CharField(max_length=3000)),
            ],
        ),
    ]
